@startuml

' Actor
actor User

' System modules in rectangles
rectangle {
    rectangle Ui
    rectangle "HealthBud [Main]" as Main
    rectangle seedu.healthbud.log
    rectangle seedu.healthbud.parser
    rectangle seedu.healthbud.storage
    rectangle seedu.healthbud.command
    rectangle LogList
}

' Actor interaction
User --[dotted]> Ui

' Main app calls
Main --> Ui
Main --> LogList
Main --> seedu.healthbud.storage
Main --> seedu.healthbud.parser

' UI accesses model indirectly
Ui -[dotted]> seedu.healthbud.log
Ui -[dotted]> LogList

' LogList uses:
LogList --> seedu.healthbud.log
LogList --[dotted]> seedu.healthbud.storage

' Parser and Command collaboration
seedu.healthbud.parser --> seedu.healthbud.command
seedu.healthbud.command --> LogList

' Storage handles persistence of logs
seedu.healthbud.storage --> seedu.healthbud.log

hide circle

@enduml
