@startuml
actor User
participant ":HealthBud" as HealthBud
participant ":GeneralParser" as GeneralParser
participant ":BMIParser" as BMIParser
participant ":BMICommand" as BMICommand

User -> HealthBud: "bmi weight 70kg, height is 1.75m"
activate HealthBud

HealthBud -> GeneralParser: handle input for bmi weight 70kg, height is 1.75m
activate GeneralParser

GeneralParser -> BMIParser: parse bmi weight 70kg, height is 1.75m
activate BMIParser

alt valid input
    BMIParser -> BMIParser: extract weight=70, height=1.75
    BMIParser -> BMICommand: return new BMICommand("bmi 70 /h 1.75", 70, 1.75)

else invalid input
    BMIParser -> BMIParser: throw HealthBudException\nor InvalidBmiException
end
deactivate BMIParser

GeneralParser -> BMICommand: execute()
activate BMICommand
deactivate BMICommand

GeneralParser --> HealthBud: success message
deactivate GeneralParser

HealthBud --> User: display result
deactivate HealthBud
@enduml