@startuml
' https://plantuml.com/class-diagram

' Legend:
' -->    navigability/association (used in method or field)
' ..>    dependency (used as parameter/return/throws)
' --|>   inheritance

Goals --|> Log
Goals : - static instance: Goals
Goals : - dailyWaterGoal: String
Goals : - dailyCalorieGoal: String
Goals : - weightGoal: String
Goals : - weeklyWeightProgress: String
Goals : + getInstance(): Goals
Goals : + updateGoals(water: String, calorie: String, weight: String): void
Goals : + setDailyWaterGoal(goal: String): void
Goals : + setDailyCalorieGoal(goal: String): void
Goals : + setWeightGoal(goal: String): void
Goals : + setWeeklyWeightProgress(progress: String): void
Goals : + getDailyWaterGoal(): String
Goals : + getDailyCalorieGoal(): String
Goals : + getWeightGoal(): String
Goals : + getWeeklyWeightProgress(): String
Goals : + toString(): String

AddGoalParser : + parse(goalLogs: LogList, input: String): AddGoalCommand
AddGoalParser : - addMissingParameters(input: String): String
AddGoalParser ..> Goals : uses
AddGoalParser ..> AddGoalCommand : creates
AddGoalParser ..> InvalidGoalException : throws

SingleLogCommand : - input: String
SingleLogCommand : - logList: LogList
SingleLogCommand --> LogList

AddGoalCommand --|> SingleLogCommand
AddGoalCommand : - static waterGoal: String
AddGoalCommand : - static calorieGoal: String
AddGoalCommand : - static weightGoal: String
AddGoalCommand : - static weeklyWeightProgress: String
AddGoalCommand : + AddGoalCommand(LogList, String, String, String, String)
AddGoalCommand : + execute(): void
AddGoalCommand --> Goals : uses singleton
AddGoalCommand ..> LogList : modifies
AddGoalCommand ..> Storage : calls append

@enduml
